/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Mantenimientos.MantenimientoCliente;
import Mantenimientos.MantenimientoEquipo;
import Mantenimientos.ManteniminetoServicio;
import Objetos.Cliente;
import Objetos.EquipoLista;
import Objetos.Servicio;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastián Bermudez, Andrey Palma, Rubén Ureña
 */
public class ContrataServicio extends javax.swing.JFrame {
   
    /**
     * Creates new form Inicio
     */
    public ContrataServicio() {
        initComponents();
        //llenaLista();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        try {
            Image imag = ImageIO.read(new File(".\\src\\Imagenes\\monitor.png"));
            this.setIconImage(imag);
        } catch (IOException e) {
            System.out.println(e);
        }
    }
    
  
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ContratarServicio = new javax.swing.JLabel();
        CodigoServicio = new javax.swing.JLabel();
        CedulaClienteTxt = new javax.swing.JTextField();
        CedulaCliente = new javax.swing.JLabel();
        ContrataServicioBtn = new javax.swing.JButton();
        VolverBtn = new javax.swing.JButton();
        CodigoServicioTxt = new javax.swing.JTextField();
        InfoCliente = new javax.swing.JLabel();
        VerificaClienteBtn = new javax.swing.JButton();
        ConsultaCodigoBtn = new javax.swing.JButton();
        ListaCodigos = new javax.swing.JLabel();
        InfoEquipo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblEquipos = new javax.swing.JTable();
        btnAgregarEquipo = new javax.swing.JButton();
        btnListarEquipo = new javax.swing.JButton();
        CedulaCliente1 = new javax.swing.JLabel();
        CedulaEmpleadoTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        ContratarServicio.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ContratarServicio.setForeground(new java.awt.Color(255, 255, 255));
        ContratarServicio.setText("Contratar Servicio");

        CodigoServicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CodigoServicio.setForeground(new java.awt.Color(255, 255, 255));
        CodigoServicio.setText("Codigo de servicio a contratar:");

        CedulaCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CedulaCliente.setForeground(new java.awt.Color(255, 255, 255));
        CedulaCliente.setText("Cedula de cliente:");

        ContrataServicioBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContrataServicioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/signing-the-contract.png"))); // NOI18N
        ContrataServicioBtn.setText("Contratar Servicio");
        ContrataServicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrataServicioBtnActionPerformed(evt);
            }
        });

        VolverBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VolverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maps-and-flags.png"))); // NOI18N
        VolverBtn.setText("Volver");
        VolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBtnActionPerformed(evt);
            }
        });

        InfoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InfoCliente.setForeground(new java.awt.Color(255, 255, 255));
        InfoCliente.setText("Informacion del cliente:");

        VerificaClienteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VerificaClienteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        VerificaClienteBtn.setText("Verificar cliente");
        VerificaClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificaClienteBtnActionPerformed(evt);
            }
        });

        ConsultaCodigoBtn.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaCodigoBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConsultaCodigoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/question.png"))); // NOI18N
        ConsultaCodigoBtn.setText("Consultar Codigos");
        ConsultaCodigoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaCodigoBtnActionPerformed(evt);
            }
        });

        ListaCodigos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ListaCodigos.setForeground(new java.awt.Color(255, 255, 255));
        ListaCodigos.setText("Lista de codigos de servicio:");

        InfoEquipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InfoEquipo.setForeground(new java.awt.Color(255, 255, 255));
        InfoEquipo.setText("Informacion del equipo:");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tblClientes);

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tblServicios);

        tblEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tblEquipos);

        btnAgregarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAgregarEquipo.setText("Agregar Equipo");
        btnAgregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEquipoActionPerformed(evt);
            }
        });

        btnListarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file.png"))); // NOI18N
        btnListarEquipo.setText("Listar Equipo");
        btnListarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEquipoActionPerformed(evt);
            }
        });

        CedulaCliente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CedulaCliente1.setForeground(new java.awt.Color(255, 255, 255));
        CedulaCliente1.setText("Su Cedula:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ContrataServicioBtn)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(VerificaClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CedulaCliente)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnListarEquipo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAgregarEquipo))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VolverBtn)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CedulaCliente1)
                                        .addGap(155, 155, 155)
                                        .addComponent(CedulaEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(InfoCliente)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(ListaCodigos)
                                        .addGap(130, 130, 130))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(ConsultaCodigoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InfoEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContratarServicio)
                        .addGap(311, 311, 311))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CedulaClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CodigoServicio)
                                .addGap(18, 18, 18)
                                .addComponent(CodigoServicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContratarServicio)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(InfoEquipo)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InfoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ListaCodigos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaCodigoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarEquipo)
                            .addComponent(btnListarEquipo))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoServicio)
                            .addComponent(CodigoServicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CedulaCliente)
                            .addComponent(CedulaClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VerificaClienteBtn)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CedulaCliente1)
                            .addComponent(CedulaEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(ContrataServicioBtn)
                        .addGap(24, 24, 24)
                        .addComponent(VolverBtn)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void limpiar(){
            CedulaEmpleadoTxt.setText("");
            CedulaClienteTxt.setText("");
            CodigoServicioTxt.setText("");
        }
    
    
        private void generaTableCliente(List lista){
         String[] columnas = {"Nombre","Apellidos","Cedula","Telefono","Correo"};
            DefaultTableModel modelo = new DefaultTableModel(){public boolean isCellEditable(int row, int column){return false;}};
            modelo.setColumnIdentifiers(columnas); 
            tblClientes.setModel(modelo);
            ManteniminetoServicio ms = ManteniminetoServicio.getInstancia();
            ArrayList listaServicios = (ArrayList) lista;
            
            if (listaServicios.size()>0 && listaServicios!= null) {
                Cliente cli = null;
                Object fila[] = new Object[5];
                    for (int i = 0; i < listaServicios.size(); i++) {
                    cli = (Cliente) listaServicios.get(i);
                   
                        fila[0] = cli.getNombre();
                        fila[1] = cli.getApellidos();
                        fila[2] = cli.getCedula();
                        fila[3] = cli.getTelefono();
                        fila[4] = cli.getCorreo();
                    modelo.addRow(fila);
                }
        }
    }
    
    
        private void generaTableServicio(List lista){
         String[] columnas = {"Codigo del Servico", "Nombre del Servicio"};
            DefaultTableModel modelo = new DefaultTableModel(){public boolean isCellEditable(int row, int column){return false;}};
            modelo.setColumnIdentifiers(columnas); 
            tblServicios.setModel(modelo);
            ManteniminetoServicio ms = ManteniminetoServicio.getInstancia();
            ArrayList listaServicios = (ArrayList) lista;
            
            if (listaServicios.size()>0 && listaServicios!= null) {
                Servicio serv = null;
                Object fila[] = new Object[2];
                    for (int i = 0; i < listaServicios.size(); i++) {
                    serv = (Servicio) listaServicios.get(i);
                   
                        fila[0] = serv.getIdServicio();
                        fila[1] = serv.getNombreServicio();
                    modelo.addRow(fila);
                }
        }
    }
        
        
        private void generaTableEquipo(List lista){
         String[] columnas = {"Codigo del Equipo", "Cedula","Marca","Modelo","Tipo"};
            DefaultTableModel modelo = new DefaultTableModel(){public boolean isCellEditable(int row, int column){return false;}};
            modelo.setColumnIdentifiers(columnas); 
            tblEquipos.setModel(modelo);
            ManteniminetoServicio ms = ManteniminetoServicio.getInstancia();
            ArrayList listaEquipos = (ArrayList) lista;
            
            if (listaEquipos.size()>0 && listaEquipos!= null) {
                EquipoLista eq = null;
                Object fila[] = new Object[5];
                    for (int i = 0; i < listaEquipos.size(); i++) {
                    eq = (EquipoLista) listaEquipos.get(i);
                   
                        fila[0] = eq.getIdEquipo();
                        fila[1] = eq.getCedula();
                        fila[2] = eq.getMarca();
                        fila[3] = eq.getModelo();
                        fila[4] = eq.getTipo();
                    modelo.addRow(fila);
                }
        }
    }
    
    
    private void ConsultaCodigoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCodigoBtnActionPerformed
        try {
            ManteniminetoServicio ms = ManteniminetoServicio.getInstancia();
            generaTableServicio(ms.listarServicio());
        } catch (Exception e) {
            System.out.println(""+e);
        }
    }//GEN-LAST:event_ConsultaCodigoBtnActionPerformed

    private void VerificaClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificaClienteBtnActionPerformed
        try {
            if (!CedulaClienteTxt.getText().isEmpty()) {
                MantenimientoCliente mc = MantenimientoCliente.getInstancia();
                int resVerifica = mc.verificaCliente(CedulaClienteTxt.getText());
                System.out.println(""+CedulaClienteTxt.getText());
                if ( resVerifica == 1) {
                    generaTableCliente(mc.listarCliente(CedulaClienteTxt.getText()));
                }else{
                    int resultado = JOptionPane.showConfirmDialog(rootPane, "Cliente no registrado. \n Desea Agregarlo?");
                    if(resultado==JOptionPane.YES_OPTION){
                        ClienteJF cjf = new ClienteJF();
                        cjf.show();
                    }
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Llene el camopo solicitado");
            }
        } catch(NumberFormatException ne){
            System.out.println(""+ne);
        }catch (Exception e) {
            System.out.println(""+e);
        }
    }//GEN-LAST:event_VerificaClienteBtnActionPerformed

    private void VolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBtnActionPerformed
        ServicioCliente sc = new ServicioCliente();
        sc.show();
        this.dispose();
    }//GEN-LAST:event_VolverBtnActionPerformed

    private void ContrataServicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrataServicioBtnActionPerformed
        try{
        if (!(CedulaClienteTxt.getText().isEmpty()||CedulaEmpleadoTxt.getText().isEmpty()||CodigoServicioTxt.getText().isEmpty())) {
            MantenimientoCliente mc = MantenimientoCliente.getInstancia();
            mc.insertaServicioCliente(Integer.parseInt(CodigoServicioTxt.getText()), CedulaClienteTxt.getText(), CedulaEmpleadoTxt.getText());
            limpiar();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Llene los campos solicitados");
        }
        }catch(NumberFormatException ne){
            JOptionPane.showMessageDialog(rootPane, "En los campos que se le solicitan los codigos solo puede insertar numeros");
            System.out.println(""+ne);
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_ContrataServicioBtnActionPerformed

    private void btnAgregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEquipoActionPerformed
        EquipoJF e =new EquipoJF();
        e.show();
    }//GEN-LAST:event_btnAgregarEquipoActionPerformed

    private void btnListarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEquipoActionPerformed
        try {
            MantenimientoEquipo me = MantenimientoEquipo.getInstancia();
            generaTableEquipo(me.listaEquipo());
        } catch (Exception e) {
            System.out.println(""+e);
        }
    }//GEN-LAST:event_btnListarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContrataServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContrataServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContrataServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContrataServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContrataServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CedulaCliente;
    private javax.swing.JLabel CedulaCliente1;
    private javax.swing.JTextField CedulaClienteTxt;
    private javax.swing.JTextField CedulaEmpleadoTxt;
    private javax.swing.JLabel CodigoServicio;
    private javax.swing.JTextField CodigoServicioTxt;
    private javax.swing.JButton ConsultaCodigoBtn;
    private javax.swing.JButton ContrataServicioBtn;
    private javax.swing.JLabel ContratarServicio;
    private javax.swing.JLabel InfoCliente;
    private javax.swing.JLabel InfoEquipo;
    private javax.swing.JLabel ListaCodigos;
    private javax.swing.JButton VerificaClienteBtn;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JButton btnAgregarEquipo;
    private javax.swing.JButton btnListarEquipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblEquipos;
    private javax.swing.JTable tblServicios;
    // End of variables declaration//GEN-END:variables
}
