/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import Objetos.Servicio;
import Mantenimientos.ManteniminetoServicio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastián Bermudez, Andrey Palma, Rubén Ureña
 */
public class ServicioJF extends javax.swing.JFrame {
   
    private Servicio serv = null;
    /**
     * Creates new form Servicios
     */
    public ServicioJF() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        
        try {
            Image imag = ImageIO.read(new File(".\\src\\Imagenes\\monitor.png"));
            this.setIconImage(imag);
        } catch (IOException e) {
            System.out.println("Fallo poner icono de la aplicacion");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Servicios = new javax.swing.JLabel();
        NombreServicio = new javax.swing.JLabel();
        NombreServicioTxt = new javax.swing.JTextField();
        TipoServicio = new javax.swing.JLabel();
        TipoServicioTxt = new javax.swing.JTextField();
        PrecioServicio = new javax.swing.JLabel();
        PrecioServicioTxt = new javax.swing.JTextField();
        AgregarModificarServicio = new javax.swing.JLabel();
        VolverBtn = new javax.swing.JButton();
        AgregarBtn = new javax.swing.JButton();
        ConsultaServiciosBtn = new javax.swing.JButton();
        ListaDeServicios = new javax.swing.JLabel();
        EliminarBtn = new javax.swing.JButton();
        CodigoEliminar = new javax.swing.JLabel();
        CodigoEliminarTxt = new javax.swing.JTextField();
        EliminarServicio = new javax.swing.JLabel();
        ModificarBtn = new javax.swing.JButton();
        Propiedades = new javax.swing.JLabel();
        Propiedades2 = new javax.swing.JLabel();
        Propiedades3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(953, 553));

        Servicios.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Servicios.setText("Servicios");

        NombreServicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NombreServicio.setForeground(new java.awt.Color(255, 255, 255));
        NombreServicio.setText("Nombre del servicio:");

        TipoServicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TipoServicio.setForeground(new java.awt.Color(255, 255, 255));
        TipoServicio.setText("Tipo del servicio:");

        PrecioServicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PrecioServicio.setForeground(new java.awt.Color(255, 255, 255));
        PrecioServicio.setText("Precio del servicio:");

        AgregarModificarServicio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AgregarModificarServicio.setForeground(new java.awt.Color(255, 255, 255));
        AgregarModificarServicio.setText("Agregar/Modificar servicio");

        VolverBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VolverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maps-and-flags.png"))); // NOI18N
        VolverBtn.setText("Volver");
        VolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBtnActionPerformed(evt);
            }
        });

        AgregarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgregarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        AgregarBtn.setText("Agregar");
        AgregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBtnActionPerformed(evt);
            }
        });

        ConsultaServiciosBtn.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaServiciosBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConsultaServiciosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/question.png"))); // NOI18N
        ConsultaServiciosBtn.setText("Consultar servicios");
        ConsultaServiciosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaServiciosBtnActionPerformed(evt);
            }
        });

        ListaDeServicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ListaDeServicios.setForeground(new java.awt.Color(255, 255, 255));
        ListaDeServicios.setText("Lista de servicios:");

        EliminarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EliminarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel-button.png"))); // NOI18N
        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        CodigoEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CodigoEliminar.setForeground(new java.awt.Color(255, 255, 255));
        CodigoEliminar.setText("Codigo de servicio a eliminar:");

        EliminarServicio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EliminarServicio.setForeground(new java.awt.Color(255, 255, 255));
        EliminarServicio.setText("Eliminar servicio");

        ModificarBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ModificarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pencil-and-paper.png"))); // NOI18N
        ModificarBtn.setText("Modificar");
        ModificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBtnActionPerformed(evt);
            }
        });

        Propiedades.setForeground(new java.awt.Color(255, 255, 255));
        Propiedades.setText("* Si desea modificar un servicio, en los espacios disponibles coloque el código de servicio que desea modificar y en la casilla correspondiente");

        Propiedades2.setForeground(new java.awt.Color(255, 255, 255));
        Propiedades2.setText("desea cambiar el texto por el que lo va a sustituir.");

        Propiedades3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Propiedades3.setForeground(new java.awt.Color(255, 255, 255));
        Propiedades3.setText("*");

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblServicios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(CodigoEliminar)
                .addGap(18, 18, 18)
                .addComponent(CodigoEliminarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminarBtn)
                .addGap(256, 256, 256))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConsultaServiciosBtn)
                .addGap(250, 250, 250))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VolverBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(Servicios))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(EliminarServicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Propiedades2)
                            .addComponent(Propiedades)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AgregarModificarServicio)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TipoServicio)
                                    .addComponent(NombreServicio)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ModificarBtn)
                                        .addComponent(PrecioServicio)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TipoServicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreServicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrecioServicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Propiedades3)
                                .addGap(60, 60, 60)
                                .addComponent(AgregarBtn)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(ListaDeServicios))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Servicios)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarModificarServicio)
                    .addComponent(ListaDeServicios))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreServicio)
                            .addComponent(NombreServicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoServicio)
                            .addComponent(TipoServicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioServicio)
                            .addComponent(PrecioServicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AgregarBtn)
                                .addComponent(ModificarBtn))
                            .addComponent(Propiedades3)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConsultaServiciosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Propiedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Propiedades2)
                .addGap(18, 18, 18)
                .addComponent(EliminarServicio)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoEliminarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarBtn)
                    .addComponent(CodigoEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolverBtn)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    private Object datosServicio(){
        try{
        if(TipoServicioTxt.getText().isEmpty()||PrecioServicioTxt.getText().isEmpty()||NombreServicioTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Debe de asegurarse de llenar todos los campos");
        }else{
            serv = new Servicio();
            serv.setTipoServicio(TipoServicioTxt.getText());
            serv.setCosto(Double.parseDouble(PrecioServicioTxt.getText()));
            serv.setNombreServicio(NombreServicioTxt.getText());
        }
        }catch(NumberFormatException ne){
            System.out.println(""+ne);
            JOptionPane.showMessageDialog(rootPane,"En costo solo se aceptan numeros");
        }catch(Exception e){
            System.out.println(""+e);
        }
        return serv;
    }
    private void limpiarCampos(){
        TipoServicioTxt.setText("");
        NombreServicioTxt.setText("");
        PrecioServicioTxt.setText("");
    }
    private void generaTableServicio(){
         String[] columnas = {"Codigo del Servico", "Tipo de Servicio",  "Costo del Servico",  "Nombre del Servicio"};
            DefaultTableModel modelo = new DefaultTableModel(){public boolean isCellEditable(int row, int column){return false;}};
            modelo.setColumnIdentifiers(columnas); 
            tblServicios.setModel(modelo);
            ManteniminetoServicio ms = ManteniminetoServicio.getInstancia();
            ArrayList listaServicios = (ArrayList) ms.listarServicio();
            
            if (listaServicios.size()>0 && listaServicios!= null) {
                Servicio serv = null;
                Object fila[] = new Object[4];
                    for (int i = 0; i < listaServicios.size(); i++) {
                    serv = (Servicio) listaServicios.get(i);
                   
                        fila[0] = serv.getIdServicio();
                        fila[1] = serv.getTipoServicio();
                        fila[2] = serv.getCosto();
                        fila[3] = serv.getNombreServicio();
                    modelo.addRow(fila);
                }
        }
    }
    
    private void ModificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBtnActionPerformed
       try{
            if(TipoServicioTxt.getText().isEmpty()||PrecioServicioTxt.getText().isEmpty()||NombreServicioTxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Debe de asegurarse de llenar todos los campos");
            }else{
                String valor = JOptionPane.showInputDialog("Digite el Codigo del servicio que desea modificar");
                if (Integer.parseInt(valor)%1==0) {
                    serv = new Servicio();
                    serv.setIdServicio(Integer.parseInt(valor));
                    serv.setTipoServicio(TipoServicioTxt.getText());
                    serv.setCosto(Double.parseDouble(PrecioServicioTxt.getText()));
                    serv.setNombreServicio(NombreServicioTxt.getText());
                    ManteniminetoServicio ms = ManteniminetoServicio.getInstancia();
                    ms.actualizaServicio(serv);
                    limpiarCampos();
                    generaTableServicio();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Debe ingresar solamente numeros enteros");
                }

            }
       }catch(NumberFormatException ne){
           System.out.println(""+ne);
           JOptionPane.showMessageDialog(rootPane, "Debe poner numeros donde se le solicita");
       }catch(Exception e){
           System.out.println(""+e);
       }
    }//GEN-LAST:event_ModificarBtnActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        if (CodigoEliminarTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo solicitado");
        }else{
                ManteniminetoServicio ms = ManteniminetoServicio.getInstancia();
                ms.desactivaServicio(Integer.parseInt(CodigoEliminarTxt.getText()));
                CodigoEliminarTxt.setText("");
                generaTableServicio();
        }
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void ConsultaServiciosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaServiciosBtnActionPerformed
        try {
            generaTableServicio();
        } catch (Exception e) {
            System.out.println(""+e);
        }
    }//GEN-LAST:event_ConsultaServiciosBtnActionPerformed

    private void AgregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBtnActionPerformed
        if (datosServicio()==null) {
            JOptionPane.showMessageDialog(rootPane,"Error");
            limpiarCampos();
        }else{
            ManteniminetoServicio ms = ManteniminetoServicio.getInstancia();
            ms.agregarServicio(datosServicio());
            generaTableServicio();
            limpiarCampos();
        }
    }//GEN-LAST:event_AgregarBtnActionPerformed

    private void VolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBtnActionPerformed

        Administracion ad = new Administracion();
        ad.show();
        this.dispose();
    }//GEN-LAST:event_VolverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicioJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicioJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicioJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicioJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicioJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBtn;
    private javax.swing.JLabel AgregarModificarServicio;
    private javax.swing.JLabel CodigoEliminar;
    private javax.swing.JTextField CodigoEliminarTxt;
    private javax.swing.JButton ConsultaServiciosBtn;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JLabel EliminarServicio;
    private javax.swing.JLabel ListaDeServicios;
    private javax.swing.JButton ModificarBtn;
    private javax.swing.JLabel NombreServicio;
    private javax.swing.JTextField NombreServicioTxt;
    private javax.swing.JLabel PrecioServicio;
    private javax.swing.JTextField PrecioServicioTxt;
    private javax.swing.JLabel Propiedades;
    private javax.swing.JLabel Propiedades2;
    private javax.swing.JLabel Propiedades3;
    private javax.swing.JLabel Servicios;
    private javax.swing.JLabel TipoServicio;
    private javax.swing.JTextField TipoServicioTxt;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblServicios;
    // End of variables declaration//GEN-END:variables
}